version: '3.8'

services:
  # 后端 API 服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: metabox_backend
    environment:
      - DATABASE_URL=sqlite:///./metabox.db
      - VECTOR_DB_TYPE=chroma
      - CHROMA_PERSIST_DIR=./chroma_db
      - JWT_SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    networks:
      - metabox_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端 Web 服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: metabox_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - metabox_network
    restart: unless-stopped

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: metabox_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - metabox_network
    restart: unless-stopped

networks:
  metabox_network:
    driver: bridge 